/*
	Author:			Ayad Shammout
	Date:			10/19/2011
	Description:	Create Database Audit Specification
	
*/

USE [SQLAuditRepository]
GO

-- Replace the [xxxxxxx] with actual SQL Server Audit name

CREATE DATABASE AUDIT SPECIFICATION [SQLAuditRepository_DBAuditSpecs]
FOR SERVER AUDIT [xxxxxxxx]
ADD (DATABASE_OBJECT_ACCESS_GROUP),
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
ADD (AUDIT_CHANGE_GROUP),
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_CHANGE_GROUP),
ADD (DATABASE_OBJECT_CHANGE_GROUP),
ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
ADD (SCHEMA_OBJECT_CHANGE_GROUP)
WITH (STATE = ON)
GO
